#!/usr/bin/env python3
"""Generate the Ansible inventory from the static IP plan (spec section 2).

Output is written to stdout, suitable for:
    python3 scripts/generate-inventory.py > ansible/inventory/hosts.ini
"""
from __future__ import annotations

import sys
from typing import Dict, List

IP_PLAN: Dict[str, Dict[str, object]] = {
    "ctrl": {"hostname": "ctrl-node", "ip": "10.0.2.10", "groups": ["mgmt"]},
    "git-cicd": {"hostname": "git-cicd", "ip": "10.0.2.11", "groups": ["mgmt", "cicd"]},
    "k8s-cp": {"hostname": "k8s-cp", "ip": "10.0.2.20", "groups": ["k8s"]},
    "k8s-wk1": {"hostname": "k8s-wk1", "ip": "10.0.2.21", "groups": ["k8s", "k8s_workers"]},
    "k8s-wk2": {"hostname": "k8s-wk2", "ip": "10.0.2.22", "groups": ["k8s", "k8s_workers"]},
    "mlflow": {"hostname": "mlflow", "ip": "10.0.2.30", "groups": ["ml_servers"]},
    "fastapi": {"hostname": "fastapi", "ip": "10.0.2.31", "groups": ["ml_servers"]},
    "postgres": {"hostname": "postgres", "ip": "10.0.2.40", "groups": ["db"]},
    "prometheus": {"hostname": "prometheus", "ip": "10.0.2.50", "groups": ["monitoring"]},
    "grafana": {"hostname": "grafana", "ip": "10.0.2.51", "groups": ["monitoring"]},
    "training-env": {"hostname": "training-env", "ip": "10.0.2.60", "groups": ["training"]},
    "testing-env": {"hostname": "testing-env", "ip": "10.0.2.61", "groups": ["testing"]},
}

GROUPS: Dict[str, List[str]] = {
    "mgmt": ["ctrl-node", "git-cicd"],
    "k8s": ["k8s-cp", "k8s-wk1", "k8s-wk2"],
    "k8s_workers": ["k8s-wk1", "k8s-wk2"],
    "cicd": ["git-cicd"],
    "ml_servers": ["mlflow", "fastapi"],
    "db": ["postgres"],
    "monitoring": ["prometheus", "grafana"],
    "training": ["training-env"],
    "testing": ["testing-env"],
}

DEFAULT_USER = "admin"


def render(hosts: Dict[str, Dict[str, object]], groups: Dict[str, List[str]], user: str = DEFAULT_USER) -> str:
    """Render the inventory file content."""
    lines: List[str] = []
    lines.append("# Ansible inventory for the MLOps platform.")
    lines.append("# Generated by scripts/generate-inventory.py from the IP plan (spec section 2).")
    lines.append("# Private IPs are static on the 10.0.2.0/24 subnet; SSH uses key-based auth.")
    lines.append("")
    lines.append("[all:vars]")
    lines.append(f"ansible_user = {user}")
    lines.append("ansible_become = true")
    lines.append("")

    for name, meta in hosts.items():
        lines.append(f"[{name}]")
        lines.append(f"{meta['hostname']} ansible_host={meta['ip']}")
        lines.append("")

    for group, members in groups.items():
        lines.append(f"[{group}]")
        for member in members:
            lines.append(f"{member}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    inventory_user = DEFAULT_USER
    if "--user" in sys.argv:
        idx = sys.argv.index("--user")
        if idx + 1 < len(sys.argv):
            inventory_user = sys.argv[idx + 1]
    print(render(IP_PLAN, GROUPS, inventory_user))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
