#!/usr/bin/env python3
# TODO: medium - Add type hints where missing
# TODO: low - Add comprehensive docstring
# TODO: low - Add error handling for edge cases
"""Generate the Ansible inventory from the local single-host plan.

All-local edition: no cloud, no private-network IPs — every logical host maps
to 127.0.0.1 with a local connection.

Output is written to stdout, suitable for:
    python3 scripts/generate-inventory.py > ansible/inventory/hosts.ini
"""
from __future__ import annotations

import sys
from typing import Dict, List

LOCAL_IP = "127.0.0.1"

IP_PLAN: Dict[str, Dict[str, object]] = {
    "ctrl": {"hostname": "ctrl-node", "ip": LOCAL_IP, "groups": ["mgmt"]},
    "git-cicd": {"hostname": "git-cicd", "ip": LOCAL_IP, "groups": ["mgmt", "cicd"]},
    "k8s-cp": {"hostname": "k8s-cp", "ip": LOCAL_IP, "groups": ["k8s"]},
    "k8s-wk1": {"hostname": "k8s-wk1", "ip": LOCAL_IP, "groups": ["k8s", "k8s_workers"]},
    "k8s-wk2": {"hostname": "k8s-wk2", "ip": LOCAL_IP, "groups": ["k8s", "k8s_workers"]},
    "mlflow": {"hostname": "mlflow", "ip": LOCAL_IP, "groups": ["ml_servers"]},
    "fastapi": {"hostname": "fastapi", "ip": LOCAL_IP, "groups": ["ml_servers"]},
    "postgres": {"hostname": "postgres", "ip": LOCAL_IP, "groups": ["db"]},
    "prometheus": {"hostname": "prometheus", "ip": LOCAL_IP, "groups": ["monitoring"]},
    "grafana": {"hostname": "grafana", "ip": LOCAL_IP, "groups": ["monitoring"]},
    "training-env": {"hostname": "training-env", "ip": LOCAL_IP, "groups": ["training"]},
    "testing-env": {"hostname": "testing-env", "ip": LOCAL_IP, "groups": ["testing"]},
}

GROUPS: Dict[str, List[str]] = {
    "mgmt": ["ctrl-node", "git-cicd"],
    "k8s": ["k8s-cp", "k8s-wk1", "k8s-wk2"],
    "k8s_workers": ["k8s-wk1", "k8s-wk2"],
    "cicd": ["git-cicd"],
    "ml_servers": ["mlflow", "fastapi"],
    "db": ["postgres"],
    "monitoring": ["prometheus", "grafana"],
    "training": ["training-env"],
    "testing": ["testing-env"],
}

DEFAULT_USER = "gadour"


def render(hosts: Dict[str, Dict[str, object]], groups: Dict[str, List[str]], user: str = DEFAULT_USER) -> str:
    """Render the inventory file content."""
    lines: List[str] = []
    lines.append("# Ansible inventory for the MLOps platform — ALL-LOCAL EDITION.")
    lines.append("# Generated by scripts/generate-inventory.py from the local single-host plan.")
    lines.append("# Every logical host maps to 127.0.0.1 with a local connection.")
    lines.append("")
    lines.append("[all:vars]")
    lines.append(f"ansible_user = {user}")
    lines.append("ansible_connection = local")
    lines.append("ansible_become = true")
    lines.append("")

    for name, meta in hosts.items():
        lines.append(f"[{name}]")
        lines.append(f"{meta['hostname']} ansible_host={meta['ip']}")
        lines.append("")

    for group, members in groups.items():
        lines.append(f"[{group}]")
        for member in members:
            lines.append(f"{member}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    inventory_user = DEFAULT_USER
    if "--user" in sys.argv:
        idx = sys.argv.index("--user")
        if idx + 1 < len(sys.argv):
            inventory_user = sys.argv[idx + 1]
    print(render(IP_PLAN, GROUPS, inventory_user))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
