apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: mlops
data:
  MLFLOW_TRACKING_URI: "http://localhost:5000"
  MODEL_NAME: "maintenance-model"
  MODEL_STAGE: "Production"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_NAME: "mlops"
  PROMETHEUS_MULTIPROC_DIR: "/tmp"
